services:
  reverse_proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontend
      - backend

  ws1:
    image: node:20.15.0-slim
    working_dir: /usr/src/nodeapp
    volumes:
      - ./node_web:/usr/src/nodeapp
    command: bash -c "npm install && node index.js"
    networks:
      - backend

  ws2:
    image: node:20.15.0-slim
    working_dir: /usr/src/nodeapp
    volumes:
      - ./node_web_about:/usr/src/nodeapp
    command: bash -c "npm install && node index.js"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge